void optiuniUser(char* , char* , char* , char *,int , int ,struct lista* ,struct lista* ,struct lista* );
void opuser();
void optiuniAdministrator(char* , char* , char* , char *, struct lista* , struct lista* , struct lista* );
void opadmin();
void paginaPrincipala(char* , char* , char* , char *,struct lista* ,struct lista* , struct lista* );
void adaugareRaspunsScurt(char* );
void opprinicipala();
int verificareParolaAdministrator(char *);
void stocareIntrebari(int* , int* , char* , char* , char* , struct lista* , struct lista* );
void incepeQuiz(int , int , char* , char* , char* , struct lista* , struct lista* , struct lista* );
void optiuniQuiz();
void transformaDinLitereMari(char s[]);
void afisareClasament(struct lista *);
int cautare(char s[], char*);
void alcatuireClasament(char* ,struct lista *);
void tipIntrebare(char* , char* , char* , char *, struct lista* , struct lista* , struct lista* );
void tipIntrebareQ();
void adaugareRaspunsMultiplu(char* );
void afisareVariante(char auxx[],char corect[]);
int validareInput(char optiune[]);
void stergeLista(struct lista *);
void reguli();
int quizScurt(int ,struct lista* );
int quizGrila(int ,struct lista* );
void generareNumere(int aparitii[], int );
int verificaAparitii(int aparitii[], int );
void afisareIntrebari(struct lista* , struct lista* , int , int* );
void citireIndecsi(int* , int);
void stergeScurte(struct lista*);
void stergeGrile(struct lista*);
int verifScurtNesterse(struct lista*);
int verifGrilaNestearsa(struct lista* );
void stergereIntrebari(struct lista* , struct lista* , int* , int ,int );
void confirmareStergere(int , int* , int* );
char* initializare();
void numeFisiere(char* , char* , char* , char *);
void schimbareParolaAdmin(char* );
void adaugareIntrebariGrila(char* ,int * ,struct lista* );
void adaugareIntrebariScurte(char* ,int * ,struct lista* );
void citireVar(char* , char* , char* , char* , char* );