void optiuniUser(char* clasament, char* intrebariScurte, char* intrebariGrila, char *parolaAdmin);
void opuser();
void optiuniAdministrator(char* clasament, char* intrebariScurte, char* intrebariGrila, char *parolaAdmin);
void opadmin();
void paginaPrincipala(char* clasament, char* intrebariScurte, char* intrebariGrila, char *parolaAdmin);
void adaugareRaspunsScurt(char* intrebariScurte);
void opprinicipala();
int verificareParolaAdministrator(char *parolaAdmin);
void stocareIntrebari(int* contorIntrebariScurt, int* contorIntrebariGrila, char* clasament, char* intrebariScurte, char* intrebariGrila);
void incepeQuiz(int contorIntrebariScurt, int contorIntrebariGrila, char* clasament, char* intrebariScurte, char* intrebariGrila);
void optiuniQuiz();
void transformaDinLitereMari(char s[]);
void afisareClasament();
int cautare(char s[], char* clasament);
void alcatuireClasament(char* clasament);
void tipIntrebare(char* clasament, char* intrebariScurte, char* intrebariGrila, char *parolaAdmin);
void tipIntrebareQ();
void adaugareRaspunsMultiplu(char* intrebariGrila);
void afisareVariante(char auxx[],char corect[]);
int validareInput(char optiune[]);
void stergeLista();
void reguli();
int quizScurt(int contorIntrebariScurt);
int quizGrila(int contorIntrebariGrila);
void generareNumere(int aparitii[], int maxNrIntrebari);
int verificaAparitii(int aparitii[], int maxNrIntrebari);
void stergereIntrebareScurt(char* intreabariScurt);
void afisareIntrebari(char** mat, int n);
char** initializareMatrice();
void citireIndecsi(int* ind, int* k, int index);
void completareInFisier(int* ind, int k, char** matrice, int index, char* intrebariScurt);
int cautareBinara(int val, int* ind, int k);
void sortare(int* ind, int k);
void stergereIntrebareGrila(char* intrebariGrila);
void afisareIntrebariGrila(char** matrice, int index);
void completareInFisierGrila(int* ind, int k, char** matrice, int index, char* intrebariGrila);
char* initializare();
void numeFisiere(char* clasament, char* intrebariScurte, char* intrebariGrila, char *parolaAdmin);
void schimbareParolaAdmin(char* parolaAdmin);
void adaugareIntrebariGrila(char* intrebariGrila,int * contorIntrebariGrila);
void adaugareIntrebariScurte(char* intrebariScurt,int * contorIntrebariScurt);
void citireVar(char* intrebare, char* raspuns1, char* raspuns2, char* raspuns3, char* corect);